[FEATURE] Add new pricing to our website
LookinLabs/LookinLabs-Web pull request #98
Opened 2024-10-11 21:38 UTC by KostLinux

# Description
Added pricing to our page

#103

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas (optional)
- [ ] I have made corresponding changes to the documentation (optional)
- [x] My changes generate no new warnings
- [ ] I've performed/added tests/lints that prove my fix is effective or that my feature works (optional)

Before creating pull request, look that all points under checklist are done!

2024-10-16 06:38 UTC, Dan-I-El requested changes

2024-10-18 18:08 UTC, Matrix278 submitted a review, later dismissed
Looks cool for me

2024-12-21 23:37 UTC, Dan-I-El requested changes

2024-12-21 23:37 UTC, Dan-I-El commented on resources/translations/ee.json
> +  "pricing_early_bird_description": "Ole üks esimene 10st liitujast!",
siin peaks olema ikkagi 5, mitte 10

2024-12-22 14:39 UTC, Matrix278 approved these changes

2024-12-22 16:40 UTC, Dan-I-El approved these changes

2024-12-22 16:43 UTC, merged